
[Interface]
PrivateKey = 2FoNtUoYHBB8doyw+7xVH1XYcHIPcORNSd4Db8Rf2WQ=
Address = 10.8.0.17/24
DNS = 1.1.1.1


[Peer]
PublicKey = E48NEcKaZeL97HwU3BFeouKM3E+rFphBMU0rrLPBzyI=
PresharedKey = Ou8bS1Gp7X/iJXR3D6OhfWNW5NI/PNFuPkJ31pybQek=
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = 217.142.136.244:51820