
[Interface]
PrivateKey = UPdd8yyJjVaEAySYAze1SxkpUAM+sa3WoA6a92M1RUE=
Address = 10.8.0.16/24
DNS = 1.1.1.1


[Peer]
PublicKey = E48NEcKaZeL97HwU3BFeouKM3E+rFphBMU0rrLPBzyI=
PresharedKey = QEL2Qbni5PsS8vIFqqGAtDPubwu3lRr4BdKsKYIm/KI=
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = 217.142.136.244:51820